apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nautilus
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-nautilus
            image: nginx:latest
            command: ["/bin/sh"]
            args: ["-c", "echo Welcome to xfusioncorp!"]
          restartPolicy: OnFailure
