apiVersion: v1
kind: Secret
metadata:
  name: beta
type: Opaque
data:
  beta.txt: |-
    <base64-encoded content of beta.txt>
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
spec:
  containers:
    - name: secret-container-xfusion
      image: centos:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: secret-volume
          mountPath: "/opt/demo"
  volumes:
    - name: secret-volume
      secret:
        secretName: beta
