apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios-deployment
spec:
  selector:
    matchLabels:
      app: nagios
  replicas: 1
  template:
    metadata:
      labels:
        app: nagios
    spec:
      containers:
        - name: nagios-container
          image: jasonrivers/nagios
---
apiVersion: v1
kind: Service
metadata:
  name: nagios-service
spec:
  type: NodePort
  selector:
    app: nagios
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
