apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-devops
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/security

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-devops
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-devops
  labels:
    app: web-devops
spec:
  volumes:
    - name: devops-volume
      persistentVolumeClaim:
        claimName: pvc-devops
  containers:
    - name: container-devops
      image: httpd:latest
      volumeMounts:
        - name: devops-volume
          mountPath: /var/www/html

---
apiVersion: v1
kind: Service
metadata:
  name: web-devops
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: web-devops
