apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-xfusion
spec:
  template:
    metadata:
      name: countdown-xfusion
    spec:
      restartPolicy: Never
      containers:
      - name: container-countdown-xfusion
        image: centos:latest
        command: ["/bin/bash", "-c", "for i in 10 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"]
